### ISSUE TITLE
Extra println! in "refresh_auth"

### ISSUE THREAD

**Issue by norcalli** [fairingrey/rustpixiv#5]
https://github.com/fairingrey/rustpixiv/blob/15bf06c36b719788ad7dc7091e77d3759fd74379/src/lib.rs#L393

This probably should be removed or hidden behind some kind of debug gating (although I don't know what the standard way to do this is).

Thank you for the crate btw.

**Comment by fairingrey** [comment]
Oh, right, thanks!

Yeah, I use the log crate for things like that now, but I was trying to figure out a quick way to see the response at the time and just wanted to dump it to stdout. Feel free to make a PR to remove it (and maybe even replace it with a `debug!` macro if you want) and I can accept it.

I'll get around to it soon, otherwise.

**Comment by fairingrey** [comment]
Handled in https://github.com/fairingrey/rustpixiv/commit/2d1106978fbe663c744988ab3a48257ea46b5eec
